// 國家名稱到 ISO 3166-1-alpha-2 代碼的映射
// 用於顯示國旗圖標
export const COUNTRY_TO_ISO: Record<string, string> = {
  // 美洲
  '巴拉圭': 'py',
  'Paraguay': 'py',
  '加拿大': 'ca',
  'Canada': 'ca',
  '智利': 'cl',
  'Chile': 'cl',
  '哥倫比亞': 'co',
  'Colombia': 'co',
  '墨西哥': 'mx',
  'Mexico': 'mx',
  '美國': 'us',
  'United States': 'us',
  '阿根廷': 'ar',
  'Argentina': 'ar',
  '巴西': 'br',
  'Brazil': 'br',
  '哥斯大黎加': 'cr',
  'Costa Rica': 'cr',
  '多明尼加': 'do',
  'Dominican Republic': 'do',
  '厄瓜多': 'ec',
  'Ecuador': 'ec',
  '薩爾瓦多': 'sv',
  'El Salvador': 'sv',
  '瓜地馬拉': 'gt',
  'Guatemala': 'gt',
  '宏都拉斯': 'hn',
  'Honduras': 'hn',
  '尼加拉瓜': 'ni',
  'Nicaragua': 'ni',
  '巴拿馬': 'pa',
  'Panama': 'pa',
  '秘魯': 'pe',
  'Peru': 'pe',
  '烏拉圭': 'uy',
  'Uruguay': 'uy',
  '委內瑞拉': 've',
  'Venezuela': 've',
  '玻利維亞': 'bo',
  'Bolivia': 'bo',
  '古巴': 'cu',
  'Cuba': 'cu',
  '海地': 'ht',
  'Haiti': 'ht',
  '牙買加': 'jm',
  'Jamaica': 'jm',
  '千里達及托巴哥': 'tt',
  'Trinidad and Tobago': 'tt',
  '巴哈馬': 'bs',
  'Bahamas': 'bs',
  '巴貝多': 'bb',
  'Barbados': 'bb',
  '貝里斯': 'bz',
  'Belize': 'bz',
  '多米尼克': 'dm',
  'Dominica': 'dm',
  '格瑞那達': 'gd',
  'Grenada': 'gd',
  '蓋亞那': 'gy',
  'Guyana': 'gy',
  '聖露西亞': 'lc',
  'Saint Lucia': 'lc',
  '聖文森及格瑞那丁': 'vc',
  'Saint Vincent and the Grenadines': 'vc',
  '蘇利南': 'sr',
  'Suriname': 'sr',
  '安地卡及巴布達': 'ag',
  'Antigua and Barbuda': 'ag',
  '聖克里斯多福及尼維斯': 'kn',
  'Saint Kitts and Nevis': 'kn',

  // 亞洲
  '香港': 'hk',
  'Hong Kong': 'hk',
  '印尼': 'id',
  'Indonesia': 'id',
  '日本': 'jp',
  'Japan': 'jp',
  '南韓': 'kr',
  'South Korea': 'kr',
  '韓國': 'kr',
  'Korea': 'kr',
  '中國': 'cn',
  'China': 'cn',
  '馬來西亞': 'my',
  'Malaysia': 'my',
  '新加坡': 'sg',
  'Singapore': 'sg',
  '泰國': 'th',
  'Thailand': 'th',
  '土耳其': 'tr',
  'Turkey': 'tr',
  '以色列': 'il',
  'Israel': 'il',
  '阿富汗': 'af',
  'Afghanistan': 'af',
  '孟加拉': 'bd',
  'Bangladesh': 'bd',
  '不丹': 'bt',
  'Bhutan': 'bt',
  '汶萊': 'bn',
  'Brunei': 'bn',
  '柬埔寨': 'kh',
  'Cambodia': 'kh',
  '東帝汶': 'tl',
  'East Timor': 'tl',
  '印度': 'in',
  'India': 'in',
  '伊朗': 'ir',
  'Iran': 'ir',
  '伊拉克': 'iq',
  'Iraq': 'iq',
  '約旦': 'jo',
  'Jordan': 'jo',
  '哈薩克': 'kz',
  'Kazakhstan': 'kz',
  '科威特': 'kw',
  'Kuwait': 'kw',
  '吉爾吉斯': 'kg',
  'Kyrgyzstan': 'kg',
  '寮國': 'la',
  'Laos': 'la',
  '黎巴嫩': 'lb',
  'Lebanon': 'lb',
  '馬爾地夫': 'mv',
  'Maldives': 'mv',
  '蒙古': 'mn',
  'Mongolia': 'mn',
  '緬甸': 'mm',
  'Myanmar': 'mm',
  '尼泊爾': 'np',
  'Nepal': 'np',
  '阿曼': 'om',
  'Oman': 'om',
  '巴基斯坦': 'pk',
  'Pakistan': 'pk',
  '巴勒斯坦': 'ps',
  'Palestine': 'ps',
  '菲律賓': 'ph',
  'Philippines': 'ph',
  '卡達': 'qa',
  'Qatar': 'qa',
  '沙烏地阿拉伯': 'sa',
  'Saudi Arabia': 'sa',
  '斯里蘭卡': 'lk',
  'Sri Lanka': 'lk',
  '敘利亞': 'sy',
  'Syria': 'sy',
  '塔吉克': 'tj',
  'Tajikistan': 'tj',
  '阿拉伯聯合大公國': 'ae',
  'United Arab Emirates': 'ae',
  '烏茲別克': 'uz',
  'Uzbekistan': 'uz',
  '越南': 'vn',
  'Vietnam': 'vn',
  '葉門': 'ye',
  'Yemen': 'ye',
  '巴林': 'bh',
  'Bahrain': 'bh',
  '北韓': 'kp',
  'North Korea': 'kp',
  '土庫曼': 'tm',
  'Turkmenistan': 'tm',
  '亞塞拜然': 'az',
  'Azerbaijan': 'az',

  // 歐洲
  '比利時': 'be',
  'Belgium': 'be',
  '捷克': 'cz',
  'Czech Republic': 'cz',
  '丹麥': 'dk',
  'Denmark': 'dk',
  '芬蘭': 'fi',
  'Finland': 'fi',
  '法國': 'fr',
  'France': 'fr',
  '德國': 'de',
  'Germany': 'de',
  '匈牙利': 'hu',
  'Hungary': 'hu',
  '愛爾蘭': 'ie',
  'Ireland': 'ie',
  '義大利': 'it',
  'Italy': 'it',
  '拉脫維亞': 'lv',
  'Latvia': 'lv',
  '立陶宛': 'lt',
  'Lithuania': 'lt',
  '荷蘭': 'nl',
  'Netherlands': 'nl',
  '挪威': 'no',
  'Norway': 'no',
  '波蘭': 'pl',
  'Poland': 'pl',
  '葡萄牙': 'pt',
  'Portugal': 'pt',
  '俄羅斯': 'ru',
  'Russia': 'ru',
  '斯洛伐克': 'sk',
  'Slovakia': 'sk',
  '西班牙': 'es',
  'Spain': 'es',
  '瑞典': 'se',
  'Sweden': 'se',
  '瑞士': 'ch',
  'Switzerland': 'ch',
  '英國': 'gb',
  'United Kingdom': 'gb',
  '奧地利': 'at',
  'Austria': 'at',
  '安道爾': 'ad',
  'Andorra': 'ad',
  '聖馬利諾': 'sm',
  'San Marino': 'sm',
  '摩納哥': 'mc',
  'Monaco': 'mc',
  '阿爾巴尼亞': 'al',
  'Albania': 'al',
  '亞美尼亞': 'am',
  'Armenia': 'am',
  '白俄羅斯': 'by',
  'Belarus': 'by',
  '波士尼亞與赫塞哥維納': 'ba',
  'Bosnia and Herzegovina': 'ba',
  '保加利亞': 'bg',
  'Bulgaria': 'bg',
  '克羅埃西亞': 'hr',
  'Croatia': 'hr',
  '賽普勒斯': 'cy',
  'Cyprus': 'cy',
  '愛沙尼亞': 'ee',
  'Estonia': 'ee',
  '喬治亞': 'ge',
  'Georgia': 'ge',
  '希臘': 'gr',
  'Greece': 'gr',
  '冰島': 'is',
  'Iceland': 'is',
  '科索沃': 'xk',
  'Kosovo': 'xk',
  '列支敦斯登': 'li',
  'Liechtenstein': 'li',
  '盧森堡': 'lu',
  'Luxembourg': 'lu',
  '馬爾他': 'mt',
  'Malta': 'mt',
  '摩爾多瓦': 'md',
  'Moldova': 'md',
  '蒙特內哥羅': 'me',
  'Montenegro': 'me',
  '北馬其頓': 'mk',
  'North Macedonia': 'mk',
  '羅馬尼亞': 'ro',
  'Romania': 'ro',
  '塞爾維亞': 'rs',
  'Serbia': 'rs',
  '斯洛維尼亞': 'si',
  'Slovenia': 'si',
  '烏克蘭': 'ua',
  'Ukraine': 'ua',
  '梵蒂岡': 'va',
  'Vatican City': 'va',

  // 非洲
  '南非': 'za',
  'South Africa': 'za',
  '埃及': 'eg',
  'Egypt': 'eg',
  '摩洛哥': 'ma',
  'Morocco': 'ma',
  '迦納': 'gh',
  'Ghana': 'gh',
  '肯亞': 'ke',
  'Kenya': 'ke',
  '坦尚尼亞': 'tz',
  'Tanzania': 'tz',
  '烏干達': 'ug',
  'Uganda': 'ug',
  '盧安達': 'rw',
  'Rwanda': 'rw',
  '衣索比亞': 'et',
  'Ethiopia': 'et',
  '奈及利亞': 'ng',
  'Nigeria': 'ng',
  '塞內加爾': 'sn',
  'Senegal': 'sn',
  '突尼西亞': 'tn',
  'Tunisia': 'tn',
  '阿爾及利亞': 'dz',
  'Algeria': 'dz',
  '安哥拉': 'ao',
  'Angola': 'ao',
  '貝南': 'bj',
  'Benin': 'bj',
  '波札那': 'bw',
  'Botswana': 'bw',
  '布吉納法索': 'bf',
  'Burkina Faso': 'bf',
  '蒲隆地': 'bi',
  'Burundi': 'bi',
  '維德角': 'cv',
  'Cabo Verde': 'cv',
  '喀麥隆': 'cm',
  'Cameroon': 'cm',
  '中非共和國': 'cf',
  'Central African Republic': 'cf',
  '查德': 'td',
  'Chad': 'td',
  '葛摩': 'km',
  'Comoros': 'km',
  '剛果民主共和國': 'cd',
  'Democratic Republic of the Congo': 'cd',
  '剛果共和國': 'cg',
  'Republic of the Congo': 'cg',
  '象牙海岸': 'ci',
  'Côte d\'Ivoire': 'ci',
  '吉布地': 'dj',
  'Djibouti': 'dj',
  '赤道幾內亞': 'gq',
  'Equatorial Guinea': 'gq',
  '厄利垂亞': 'er',
  'Eritrea': 'er',
  '史瓦帝尼': 'sz',
  'Eswatini': 'sz',
  '加彭': 'ga',
  'Gabon': 'ga',
  '甘比亞': 'gm',
  'Gambia': 'gm',
  '幾內亞': 'gn',
  'Guinea': 'gn',
  '幾內亞比索': 'gw',
  'Guinea-Bissau': 'gw',
  '賴索托': 'ls',
  'Lesotho': 'ls',
  '賴比瑞亞': 'lr',
  'Liberia': 'lr',
  '利比亞': 'ly',
  'Libya': 'ly',
  '馬達加斯加': 'mg',
  'Madagascar': 'mg',
  '馬拉威': 'mw',
  'Malawi': 'mw',
  '馬利': 'ml',
  'Mali': 'ml',
  '茅利塔尼亞': 'mr',
  'Mauritania': 'mr',
  '模里西斯': 'mu',
  'Mauritius': 'mu',
  '莫三比克': 'mz',
  'Mozambique': 'mz',
  '納米比亞': 'na',
  'Namibia': 'na',
  '尼日': 'ne',
  'Niger': 'ne',
  '聖多美普林西比': 'st',
  'Sao Tome and Principe': 'st',
  '塞席爾': 'sc',
  'Seychelles': 'sc',
  '獅子山': 'sl',
  'Sierra Leone': 'sl',
  '索馬利亞': 'so',
  'Somalia': 'so',
  '南蘇丹': 'ss',
  'South Sudan': 'ss',
  '蘇丹': 'sd',
  'Sudan': 'sd',
  '多哥': 'tg',
  'Togo': 'tg',
  '尚比亞': 'zm',
  'Zambia': 'zm',
  '辛巴威': 'zw',
  'Zimbabwe': 'zw',

  // 大洋洲
  '澳洲': 'au',
  'Australia': 'au',
  '紐西蘭': 'nz',
  'New Zealand': 'nz',
  '斐濟': 'fj',
  'Fiji': 'fj',
  '吉里巴斯': 'ki',
  'Kiribati': 'ki',
  '馬紹爾群島': 'mh',
  'Marshall Islands': 'mh',
  '密克羅尼西亞': 'fm',
  'Micronesia': 'fm',
  '諾魯': 'nr',
  'Nauru': 'nr',
  '帛琉': 'pw',
  'Palau': 'pw',
  '巴布亞紐幾內亞': 'pg',
  'Papua New Guinea': 'pg',
  '薩摩亞': 'ws',
  'Samoa': 'ws',
  '索羅門群島': 'sb',
  'Solomon Islands': 'sb',
  '東加': 'to',
  'Tonga': 'to',
  '吐瓦魯': 'tv',
  'Tuvalu': 'tv',
  '萬那杜': 'vu',
  'Vanuatu': 'vu',
};

/**
 * 根據國家名稱獲取 ISO 3166-1-alpha-2 代碼
 * @param countryName 國家名稱（中文或英文）
 * @returns ISO 代碼（小寫），如果找不到則返回 null
 */
export function getCountryISO(countryName: string): string | null {
  return COUNTRY_TO_ISO[countryName] || null;
}

