// 國家與地區對應表
export const COUNTRY_REGION_MAP: Record<string, string> = {
  // 美洲 (Americas)
  '巴拉圭': 'Americas',
  'Paraguay': 'Americas',
  '加拿大': 'Americas',
  'Canada': 'Americas',
  '智利': 'Americas',
  'Chile': 'Americas',
  '哥倫比亞': 'Americas',
  'Colombia': 'Americas',
  '墨西哥': 'Americas',
  'Mexico': 'Americas',
  '美國': 'Americas',
  'United States': 'Americas',
  '阿根廷': 'Americas',
  'Argentina': 'Americas',
  '巴西': 'Americas',
  'Brazil': 'Americas',
  '哥斯大黎加': 'Americas',
  'Costa Rica': 'Americas',
  '多明尼加': 'Americas',
  'Dominican Republic': 'Americas',
  '厄瓜多': 'Americas',
  'Ecuador': 'Americas',
  '薩爾瓦多': 'Americas',
  'El Salvador': 'Americas',
  '瓜地馬拉': 'Americas',
  'Guatemala': 'Americas',
  '宏都拉斯': 'Americas',
  'Honduras': 'Americas',
  '尼加拉瓜': 'Americas',
  'Nicaragua': 'Americas',
  '巴拿馬': 'Americas',
  'Panama': 'Americas',
  '秘魯': 'Americas',
  'Peru': 'Americas',
  '烏拉圭': 'Americas',
  'Uruguay': 'Americas',
  '委內瑞拉': 'Americas',
  'Venezuela': 'Americas',
  '玻利維亞': 'Americas',
  'Bolivia': 'Americas',
  '古巴': 'Americas',
  'Cuba': 'Americas',
  '海地': 'Americas',
  'Haiti': 'Americas',
  '牙買加': 'Americas',
  'Jamaica': 'Americas',
  '千里達及托巴哥': 'Americas',
  'Trinidad and Tobago': 'Americas',
  '巴哈馬': 'Americas',
  'Bahamas': 'Americas',
  '巴貝多': 'Americas',
  'Barbados': 'Americas',
  '貝里斯': 'Americas',
  'Belize': 'Americas',
  '多米尼克': 'Americas',
  'Dominica': 'Americas',
  '格瑞那達': 'Americas',
  'Grenada': 'Americas',
  '蓋亞那': 'Americas',
  'Guyana': 'Americas',
  '聖露西亞': 'Americas',
  'Saint Lucia': 'Americas',
  '聖文森及格瑞那丁': 'Americas',
  'Saint Vincent and the Grenadines': 'Americas',
  '蘇利南': 'Americas',
  'Suriname': 'Americas',
  '安地卡及巴布達': 'Americas',
  'Antigua and Barbuda': 'Americas',
  '聖克里斯多福及尼維斯': 'Americas',
  'Saint Kitts and Nevis': 'Americas',

  // 亞洲 (Asia)
  '香港': 'Asia',
  'Hong Kong': 'Asia',
  '印尼': 'Asia',
  'Indonesia': 'Asia',
  '日本': 'Asia',
  'Japan': 'Asia',
  '南韓': 'Asia',
  'South Korea': 'Asia',
  '韓國': 'Asia',
  'Korea': 'Asia',
  '中國': 'Asia',
  'China': 'Asia',
  '馬來西亞': 'Asia',
  'Malaysia': 'Asia',
  '新加坡': 'Asia',
  'Singapore': 'Asia',
  '泰國': 'Asia',
  'Thailand': 'Asia',
  '土耳其': 'Asia',
  'Turkey': 'Asia',
  '以色列': 'Asia',
  'Israel': 'Asia',
  '阿富汗': 'Asia',
  'Afghanistan': 'Asia',
  '孟加拉': 'Asia',
  'Bangladesh': 'Asia',
  '不丹': 'Asia',
  'Bhutan': 'Asia',
  '汶萊': 'Asia',
  'Brunei': 'Asia',
  '柬埔寨': 'Asia',
  'Cambodia': 'Asia',
  '東帝汶': 'Asia',
  'East Timor': 'Asia',
  '印度': 'Asia',
  'India': 'Asia',
  '伊朗': 'Asia',
  'Iran': 'Asia',
  '伊拉克': 'Asia',
  'Iraq': 'Asia',
  '約旦': 'Asia',
  'Jordan': 'Asia',
  '哈薩克': 'Asia',
  'Kazakhstan': 'Asia',
  '科威特': 'Asia',
  'Kuwait': 'Asia',
  '吉爾吉斯': 'Asia',
  'Kyrgyzstan': 'Asia',
  '寮國': 'Asia',
  'Laos': 'Asia',
  '黎巴嫩': 'Asia',
  'Lebanon': 'Asia',
  '馬爾地夫': 'Asia',
  'Maldives': 'Asia',
  '蒙古': 'Asia',
  'Mongolia': 'Asia',
  '緬甸': 'Asia',
  'Myanmar': 'Asia',
  '尼泊爾': 'Asia',
  'Nepal': 'Asia',
  '阿曼': 'Asia',
  'Oman': 'Asia',
  '巴基斯坦': 'Asia',
  'Pakistan': 'Asia',
  '巴勒斯坦': 'Asia',
  'Palestine': 'Asia',
  '菲律賓': 'Asia',
  'Philippines': 'Asia',
  '卡達': 'Asia',
  'Qatar': 'Asia',
  '沙烏地阿拉伯': 'Asia',
  'Saudi Arabia': 'Asia',
  '斯里蘭卡': 'Asia',
  'Sri Lanka': 'Asia',
  '敘利亞': 'Asia',
  'Syria': 'Asia',
  '塔吉克': 'Asia',
  'Tajikistan': 'Asia',
  '阿拉伯聯合大公國': 'Asia',
  'United Arab Emirates': 'Asia',
  '烏茲別克': 'Asia',
  'Uzbekistan': 'Asia',
  '越南': 'Asia',
  'Vietnam': 'Asia',
  '葉門': 'Asia',
  'Yemen': 'Asia',
  '巴林': 'Asia',
  'Bahrain': 'Asia',
  '北韓': 'Asia',
  'North Korea': 'Asia',
  '土庫曼': 'Asia',
  'Turkmenistan': 'Asia',
  '亞塞拜然': 'Asia',
  'Azerbaijan': 'Asia',

  // 歐洲 (Europe)
  '比利時': 'Europe',
  'Belgium': 'Europe',
  '捷克': 'Europe',
  'Czech Republic': 'Europe',
  '丹麥': 'Europe',
  'Denmark': 'Europe',
  '芬蘭': 'Europe',
  'Finland': 'Europe',
  '法國': 'Europe',
  'France': 'Europe',
  '德國': 'Europe',
  'Germany': 'Europe',
  '匈牙利': 'Europe',
  'Hungary': 'Europe',
  '愛爾蘭': 'Europe',
  'Ireland': 'Europe',
  '義大利': 'Europe',
  'Italy': 'Europe',
  '拉脫維亞': 'Europe',
  'Latvia': 'Europe',
  '立陶宛': 'Europe',
  'Lithuania': 'Europe',
  '荷蘭': 'Europe',
  'Netherlands': 'Europe',
  '挪威': 'Europe',
  'Norway': 'Europe',
  '波蘭': 'Europe',
  'Poland': 'Europe',
  '葡萄牙': 'Europe',
  'Portugal': 'Europe',
  '俄羅斯': 'Europe',
  'Russia': 'Europe',
  '斯洛伐克': 'Europe',
  'Slovakia': 'Europe',
  '西班牙': 'Europe',
  'Spain': 'Europe',
  '瑞典': 'Europe',
  'Sweden': 'Europe',
  '瑞士': 'Europe',
  'Switzerland': 'Europe',
  '英國': 'Europe',
  'United Kingdom': 'Europe',
  '奧地利': 'Europe',
  'Austria': 'Europe',
  '安道爾': 'Europe',
  'Andorra': 'Europe',
  '聖馬利諾': 'Europe',
  'San Marino': 'Europe',
  '摩納哥': 'Europe',
  'Monaco': 'Europe',
  '阿爾巴尼亞': 'Europe',
  'Albania': 'Europe',
  '亞美尼亞': 'Europe',
  'Armenia': 'Europe',
  '白俄羅斯': 'Europe',
  'Belarus': 'Europe',
  '波士尼亞與赫塞哥維納': 'Europe',
  'Bosnia and Herzegovina': 'Europe',
  '保加利亞': 'Europe',
  'Bulgaria': 'Europe',
  '克羅埃西亞': 'Europe',
  'Croatia': 'Europe',
  '賽普勒斯': 'Europe',
  'Cyprus': 'Europe',
  '愛沙尼亞': 'Europe',
  'Estonia': 'Europe',
  '喬治亞': 'Europe',
  'Georgia': 'Europe',
  '希臘': 'Europe',
  'Greece': 'Europe',
  '冰島': 'Europe',
  'Iceland': 'Europe',
  '科索沃': 'Europe',
  'Kosovo': 'Europe',
  '列支敦斯登': 'Europe',
  'Liechtenstein': 'Europe',
  '盧森堡': 'Europe',
  'Luxembourg': 'Europe',
  '馬爾他': 'Europe',
  'Malta': 'Europe',
  '摩爾多瓦': 'Europe',
  'Moldova': 'Europe',
  '蒙特內哥羅': 'Europe',
  'Montenegro': 'Europe',
  '北馬其頓': 'Europe',
  'North Macedonia': 'Europe',
  '羅馬尼亞': 'Europe',
  'Romania': 'Europe',
  '塞爾維亞': 'Europe',
  'Serbia': 'Europe',
  '斯洛維尼亞': 'Europe',
  'Slovenia': 'Europe',
  '烏克蘭': 'Europe',
  'Ukraine': 'Europe',
  '梵蒂岡': 'Europe',
  'Vatican City': 'Europe',

  // 非洲 (Africa)
  '南非': 'Africa',
  'South Africa': 'Africa',
  '埃及': 'Africa',
  'Egypt': 'Africa',
  '摩洛哥': 'Africa',
  'Morocco': 'Africa',
  '迦納': 'Africa',
  'Ghana': 'Africa',
  '肯亞': 'Africa',
  'Kenya': 'Africa',
  '坦尚尼亞': 'Africa',
  'Tanzania': 'Africa',
  '烏干達': 'Africa',
  'Uganda': 'Africa',
  '盧安達': 'Africa',
  'Rwanda': 'Africa',
  '衣索比亞': 'Africa',
  'Ethiopia': 'Africa',
  '奈及利亞': 'Africa',
  'Nigeria': 'Africa',
  '塞內加爾': 'Africa',
  'Senegal': 'Africa',
  '突尼西亞': 'Africa',
  'Tunisia': 'Africa',
  '阿爾及利亞': 'Africa',
  'Algeria': 'Africa',
  '安哥拉': 'Africa',
  'Angola': 'Africa',
  '貝南': 'Africa',
  'Benin': 'Africa',
  '波札那': 'Africa',
  'Botswana': 'Africa',
  '布吉納法索': 'Africa',
  'Burkina Faso': 'Africa',
  '蒲隆地': 'Africa',
  'Burundi': 'Africa',
  '維德角': 'Africa',
  'Cabo Verde': 'Africa',
  '喀麥隆': 'Africa',
  'Cameroon': 'Africa',
  '中非共和國': 'Africa',
  'Central African Republic': 'Africa',
  '查德': 'Africa',
  'Chad': 'Africa',
  '葛摩': 'Africa',
  'Comoros': 'Africa',
  '剛果民主共和國': 'Africa',
  'Democratic Republic of the Congo': 'Africa',
  '剛果共和國': 'Africa',
  'Republic of the Congo': 'Africa',
  '象牙海岸': 'Africa',
  'Côte d\'Ivoire': 'Africa',
  '吉布地': 'Africa',
  'Djibouti': 'Africa',
  '赤道幾內亞': 'Africa',
  'Equatorial Guinea': 'Africa',
  '厄利垂亞': 'Africa',
  'Eritrea': 'Africa',
  '史瓦帝尼': 'Africa',
  'Eswatini': 'Africa',
  '加彭': 'Africa',
  'Gabon': 'Africa',
  '甘比亞': 'Africa',
  'Gambia': 'Africa',
  '幾內亞': 'Africa',
  'Guinea': 'Africa',
  '幾內亞比索': 'Africa',
  'Guinea-Bissau': 'Africa',
  '賴索托': 'Africa',
  'Lesotho': 'Africa',
  '賴比瑞亞': 'Africa',
  'Liberia': 'Africa',
  '利比亞': 'Africa',
  'Libya': 'Africa',
  '馬達加斯加': 'Africa',
  'Madagascar': 'Africa',
  '馬拉威': 'Africa',
  'Malawi': 'Africa',
  '馬利': 'Africa',
  'Mali': 'Africa',
  '茅利塔尼亞': 'Africa',
  'Mauritania': 'Africa',
  '模里西斯': 'Africa',
  'Mauritius': 'Africa',
  '莫三比克': 'Africa',
  'Mozambique': 'Africa',
  '納米比亞': 'Africa',
  'Namibia': 'Africa',
  '尼日': 'Africa',
  'Niger': 'Africa',
  '聖多美普林西比': 'Africa',
  'Sao Tome and Principe': 'Africa',
  '塞席爾': 'Africa',
  'Seychelles': 'Africa',
  '獅子山': 'Africa',
  'Sierra Leone': 'Africa',
  '索馬利亞': 'Africa',
  'Somalia': 'Africa',
  '南蘇丹': 'Africa',
  'South Sudan': 'Africa',
  '蘇丹': 'Africa',
  'Sudan': 'Africa',
  '多哥': 'Africa',
  'Togo': 'Africa',
  '尚比亞': 'Africa',
  'Zambia': 'Africa',
  '辛巴威': 'Africa',
  'Zimbabwe': 'Africa',

  // 大洋洲 (Oceania)
  '澳洲': 'Oceania',
  'Australia': 'Oceania',
  '紐西蘭': 'Oceania',
  'New Zealand': 'Oceania',
  '斐濟': 'Oceania',
  'Fiji': 'Oceania',
  '吉里巴斯': 'Oceania',
  'Kiribati': 'Oceania',
  '馬紹爾群島': 'Oceania',
  'Marshall Islands': 'Oceania',
  '密克羅尼西亞': 'Oceania',
  'Micronesia': 'Oceania',
  '諾魯': 'Oceania',
  'Nauru': 'Oceania',
  '帛琉': 'Oceania',
  'Palau': 'Oceania',
  '巴布亞紐幾內亞': 'Oceania',
  'Papua New Guinea': 'Oceania',
  '薩摩亞': 'Oceania',
  'Samoa': 'Oceania',
  '索羅門群島': 'Oceania',
  'Solomon Islands': 'Oceania',
  '東加': 'Oceania',
  'Tonga': 'Oceania',
  '吐瓦魯': 'Oceania',
  'Tuvalu': 'Oceania',
  '萬那杜': 'Oceania',
  'Vanuatu': 'Oceania',
};

// 地區列表（不包含 Other）
export const REGIONS = [
  { value: 'Americas', label: '美洲' },
  { value: 'Europe', label: '歐洲' },
  { value: 'Asia', label: '亞洲' },
  { value: 'Africa', label: '非洲' },
  { value: 'Oceania', label: '大洋洲' },
];

// 根據國家名稱獲取地區
export function getRegionByCountry(country: string): string | null {
  return COUNTRY_REGION_MAP[country] || null;
}

// 獲取所有國家列表（按地區分組）
export function getCountriesByRegion() {
  const countriesByRegion: Record<string, string[]> = {
    Americas: [],
    Europe: [],
    Asia: [],
    Africa: [],
    Oceania: [],
  };

  Object.entries(COUNTRY_REGION_MAP).forEach(([country, region]) => {
    if (countriesByRegion[region]) {
      countriesByRegion[region].push(country);
    }
  });

  return countriesByRegion;
}
